# Generated by Django 5.0.4 on 2024-05-05 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField(max_length=255, verbose_name='タイトル1')),
                ('title2', models.TextField(max_length=255, verbose_name='タイトル2')),
                ('title3', models.TextField(blank=True, max_length=255, null=True, verbose_name='タイトル3')),
                ('title4', models.TextField(blank=True, max_length=255, null=True, verbose_name='タイトル4')),
                ('title5', models.TextField(blank=True, max_length=255, null=True, verbose_name='タイトル5')),
                ('title6', models.TextField(blank=True, max_length=255, null=True, verbose_name='タイトル6')),
                ('title7', models.TextField(blank=True, max_length=255, null=True, verbose_name='タイトル7')),
                ('title8', models.TextField(blank=True, max_length=255, null=True, verbose_name='タイトル8')),
                ('title9', models.TextField(blank=True, max_length=255, null=True, verbose_name='タイトル9')),
                ('url1', models.URLField(verbose_name='URL1')),
                ('url2', models.URLField(verbose_name='URL2')),
                ('url3', models.URLField(blank=True, null=True, verbose_name='URL3')),
                ('url4', models.URLField(blank=True, null=True, verbose_name='URL4')),
                ('url5', models.URLField(blank=True, null=True, verbose_name='URL5')),
                ('url6', models.URLField(blank=True, null=True, verbose_name='URL6')),
                ('url7', models.URLField(blank=True, null=True, verbose_name='URL7')),
                ('url8', models.URLField(blank=True, null=True, verbose_name='URL8')),
                ('url9', models.URLField(blank=True, null=True, verbose_name='URL9')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
